### ISSUE TITLE
Descrição do item

### ISSUE THREAD

**Issue by helquisson** [discovery-tecnologia/dsc-mercado-livre#18]
@dilowagner, ao enviar um item, a descrição do anúncio não vai para o Mercado Livre, no warning, menciona que está deprecated e pede pra usar plain_text: 

> [1] => stdClass Object
                        (
                            [cause_id] => 310
                            [code] => item.description.text.not_allowed
                            [message] => The text property is deprecated. And will soon be rejected. Please use plain_text
                            [references] => Array
                                (
                                    [0] => item.description
                                )

Fiz um teste usando o plain_text e funfou:

`"description" => [
	        	'plain_text' => $product->description
	        ],`

Valew até mais!!

**Comment by dilowagner** [comment]
Ola @helquisson 

Mais uma vez obrigado por contribuir...
Pelo que vi o Mercado Livre deve ter atualizado esse campo, pois antes eu enviava normalmente como 'text' - tive que adaptar pra nao quebrar pra quem usava da forma antiga...

Ajustei isso no [pull request](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/1.6.2)

Valeuuus!

**Comment by dilowagner** [comment]
Nao mudou nada...

$item = new Item();
$item->setDescription('Descricao aqui...');

**Comment by helquisson** [comment]
Valew cara, abraços!
