### ISSUE TITLE
Description Vazio

### ISSUE THREAD

**Issue by luishscosta** [discovery-tecnologia/dsc-mercado-livre#20]
Quando tento trazer o objeto do produto a descrição está vindo incompleta, há alguma maneira de trazer a descrição na mesma request?

```php
$productService->findProduct($item);
```

![image](https://user-images.githubusercontent.com/7052981/49050358-261e2e00-f1ca-11e8-9b16-3e088ca6418d.png)

Para contornar esse caso estou fazendo a request separada:

```php
$productService->findDescription($productFrom->getId());
```

**Comment by dilowagner** [comment]
Olá @luishscosta 
Tenho que verificar, se não me engano, essas descrições não são retornadas diretamente no GET do Produto mesmo...
Eu deveria ter removido o getDescriptions do mapeamento de Item.

Mas vou confirmar isso...
Obrigado por contribuir...

**Comment by luishscosta** [comment]
@dilowagner Realmente, somente traz esse código que já está correto.

https://developers.mercadolivre.com.br/pt_br/publicacao-de-produtos
