### ISSUE TITLE
Incompatibilidade com Laravel 5.7

### ISSUE THREAD

**Issue by luishscosta** [discovery-tecnologia/dsc-mercado-livre#21]
Com o travamento no commit https://github.com/discovery-tecnologia/dsc-mercado-livre/commit/5e60012fc156c96640dce2ed8ec58a00d43f0d8d onde fixou as versões dos pocotes, o Laravel 5.7 deixou de atualizar o dsc-mercado-livre por conta de conflitos.

Para contornar a situação, tive que adicionar para funcionar com versões maiores pois ele usa pacotes mais atualizados:

```php
    "doctrine/collections"     : "^v1.3.0",
    "doctrine/cache"           : "^v1.6.0",
    "doctrine/instantiator"    : "^1.0.4",
    "doctrine/annotations"     : "^v1.4.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^5.5.0"
```

**Comment by dilowagner** [comment]
Realizei o merge do pull-request #22 

Valeu @luishscosta
