### ISSUE TITLE
Mudar exposição alta para máxima e frete mercado envios

### ISSUE THREAD

**Issue by Winsten** [discovery-tecnologia/dsc-mercado-livre#26]
Boa tarde Devs!!

Uma pergunta como faço para selecionar o mercado envios? com e sem frete grátis?

Verifiquei aqui e não consegui encontrar a resposta, sei que é bem parecido com as pictures, attributes, e variations no caso como se fosse um array.

na documentação do ML está assim 
curl -X POST -H "Content-Type: application/json" -d '{
    "title": "Item de teste",
    "category_id": "MLA91727",
    "price": 1200,
    "currency_id": "ARS",
    "available_quantity": 2,
    "buying_mode": "buy_it_now",
    "listing_type_id": "bronze",
    "condition": "new",
    "description": "test",
    "pictures": [
        {
            "source": "http://upload.wikimedia.org/wikipedia/commons/f/fd/Ray_Ban_Original_Wayfarer.jpg"
        },
        {
            "source": "http://en.wikipedia.org/wiki/File:Teashades.gif"
        }
    ],
   "shipping": {
   "mode": "me2",
   "local_pick_up": false,
   "free_shipping": false,
   "free_methods": []
 }
}' https://api.mercadolibre.com/items?access_token=$ACCESS_TOKEN

**Comment by dilowagner** [comment]
Ola @Winsten 
Essa implementacao nao esta mapeada ainda... estou finalizando "Perguntas e Respostas" e em seguida realizarei esse mapeamento...

Abraco!

**Comment by Winsten** [comment]
Opa boa tarde, acabou que tive que fazer outras coisas e não respondi antes.
Eu fiz o mapeamento aqui, até que bem fácil, e gostaria de disponibilizar para todos, fiz uma nova classe e adicionei aos produtos e também atualizei o README.md.
Gostaria de saber como subo isso para o projeto, nunca contribui com projetos, só utilizo o git para projetos pessoais, bitbucket e automação de deploys. 
No mais muito obrigado, valeu !!!

**Comment by dilowagner** [comment]
Opa, que legal @Winsten 

Bom, você provavelmente fez um Fork do Projeto correto? 
- Você precisa dar um commit no branch master
- Você precisa criar um Pull Request (referenciando o seu commit)
- Com isso, vou receber uma notificação para realizar o revisão aqui....

Te aconselho criar testes unitários pra feature também! 

Nesse link tem um pequeno manual de sugestões de contribuição:
https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/master/CONTRIBUTING.md

Valeu cara abraço!
Dúvidas à disposição
