### ISSUE TITLE
Como adicionar atributos referentes a endereço?

### ISSUE THREAD

**Issue by r7alves** [discovery-tecnologia/dsc-mercado-livre#27]
No contexto que estou desenvolvendo, o anuncio é da categoria de imoveis, sendo assim tem atributos obrigatorios que nao constam na classe Item, neste caso os atributos referentes a endereço. Segue meu trecho de codigo o erro retornado:
```
public function postInMeLi()
    {
        $meli = $this->authenticateInMeLi();

        $item = new Item();
        $item->setTitle('Venda Casa 2 quartos 1 suite Bairro Mecejana')
            ->setDescription('Test item - no offer')
            ->setCategoryId('MLB1466')
            ->setPrice(1000)
            ->setCurrencyId('BRL')
            ->setAvailableQuantity(1)
            ->setBuyingMode('classified')
            ->setListingTypeId('free')
            ->setCondition('new')
            ->setWarranty('12 months');

        // Imagem do Produto
        $picture = new Picture();
        $picture->setSource('http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg');
        $item->addPicture($picture); // collection de imagens

        $announcement = new Announcement($meli);
        $response = $announcement->create($item);

        // Link do produto publicado
        echo $response->getPermalink();
    } 
```

callback
`Some errors occurred: {"message":"Validation error","error":"validation_error","status":400,"cause":[{"department":"items","cause_id":187,"type":"error","code":"item.location.invalid","references":["item.location"],"message":"Field 'location' requires up to city level. [country.name: null, state.name: null, city.name: null]"}`

**Comment by dilowagner** [comment]
Ola @r7alves 
Realmente esta esse mapeamento esta incompleto, hoje tenho a classe SellerAddres mas nao esta mapeada com o Anuncio

Vou providenciar

Valeu

**Comment by dilowagner** [comment]
Ola @r7alves 

Publiquei a [versao 1.7.2](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/1.7.2) que possui os mapeamentos para que vc consiga enviar o **Location** nos anuncios de Imoveis ou Veiculos, segue um exemplo abaixo de como vc pode realizar isso:

```php
$item = new Item();
$item->setTitle('Venda Casa 2 quartos 1 suite Bairro Mecejana')
    ->setDescription('Test item - no offer')
    ->setCategoryId('MLB253291') //MUITO IMPORTANTE: a Categoria precisa ser a ultima da hierarquia
    ->setPrice(1000)
    ->setCurrencyId('BRL')
    ->setAvailableQuantity(1)
    ->setBuyingMode('classified')
    ->setListingTypeId('free')
    ->setCondition('new')
    ->setWarranty('12 months');

// Imagem do Produto        
$picture = new Picture();
$picture->setSource('http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg');
$item->addPicture($picture); // collection de imagens

// Sera necessario enviar os dados do Pais, Estado e Cidade
// Com o AddressService voce consegue fazer isso...
$addressService = new AddressService();
// Pais
$country = $addressService->findCountry('BR');
// Estado  - no exemplo peguei Santa Catarina
$state = $country->getStates()->get(23);
// Preciso consultar a API novamente pra trazer as cidades relacionadas
$state = $addressService->findState($state->getId());
// Cidade - no exemplo peguei a primeira
$city = $state->getCities()->get(1);

// Criamos um novo Location e adicionamos ao Item
$location = new Location();
$location->setCity($city);
$location->setState($state);
$location->setCountry($country);

$item->setLocation($location);

$announcement = new Announcement($meli);
$response = $announcement->create($item);

// Link do produto publicado
echo $response->getPermalink();
```
Como voce pode perceber... eu coloquei valores "fixos" para Pais, Estado e Cidade, mas seria interessante vc criar uma logica no seu sistema para o usuario escolher estes dados dinamicamente... 

Outro detalhe eh que quando fiz meus testes aqui, alguns dados tambem sao obrigatorios de acordo com a Categoria (no meu caso, usei 'MLB253291').

[Esse link](https://github.com/discovery-tecnologia/dsc-mercado-livre/issues/9) explica um pouco como enviar o **attribute_combinations** de acordo com a Categoria

Valeu  cara, obrigado por contribuir!
