### ISSUE TITLE
Dados do usuário

### ISSUE THREAD

**Issue by laragallassi** [discovery-tecnologia/dsc-mercado-livre#29]
Sou novata com programação, tenho que juntar a api do mercado livre com o meu projeto em laravel. Achar seu código me deixou aliviada, mas não estou conseguindo utilizar direito, falha minha. No meu index do controller  `MercadoLivreController` eu coloquei o código  
`        $meli = new Meli('meuid', 'minhakey');

        $service = new UserService($meli);

        // Consulta dados do usuário
        $informations = $service->getInformationAuthenticatedUser();
           
        //dd($informations);
        return view('ml.index')->with('informations', $informations);`

Quando faço o dd as informações saem na tela certinho 
![image](https://user-images.githubusercontent.com/18129465/54613770-0e4d0d00-4a3a-11e9-94f3-b726c6a31b27.png)

Quando eu tiro o dd e faço um `<?php print_r($informations)?>` na view index o resultado é esse
![image](https://user-images.githubusercontent.com/18129465/54613898-448a8c80-4a3a-11e9-881c-6d3afc9a0919.png)

mas quando eu faço um foreach pra tentar pegar cada dado separadamente pra imprimir na tela, eu não consigo, não sai absolutamente nada do foreach.
`                        @foreach($informations as $information)
                                <tr>
                                    <td>{{ $information->id }}</td>
                                    <td>{{ $information->nickname }}</td>                   
                                </tr>
                           @endforeach`

Sabe me dizer o que estou fazendo de errado? 

Agradeço desde já!

**Comment by dilowagner** [comment]
Oi @laragallassi tudo bem!?
Entao, nesse caso eh porque vc esta usando um foreach em algo que nao eh uma Collection (array). Ao meu ver vc nao precisa usar o foreach nesse caso.... 

essa consulta traz apenas um objeto User

Tenta assim:

```php
    $service = new UserService($meli);

    // Consulta dados do usuário
    $user = $service->getInformationAuthenticatedUser();
       
    //dd($user);
    return view('ml.index')->with('user', $user);
```

```html
 <tr> 
   <td>{{ $user->id }}</td> 
   <td>{{ $user->nickname }}</td> 
 </tr>
```
Valeu, abraco

**Comment by laragallassi** [comment]
Tentei, no dd saiu perfeitamente como no outro, quando tiro o dd ele da erro 

> "Cannot access private property Dsc\MercadoLivre\Resources\User\User::$id"

**Comment by dilowagner** [comment]
Ha desculpa,
Realmente... os atributos do Objeto sao privados a classe...
Voce precisa acessa-los com get/set

```html
<tr> 
   <td>{{ $user->getId() }}</td> 
   <td>{{ $user->getNickname() }}</td> 
 </tr>
```

**Comment by laragallassi** [comment]
Muito, MUITO, obrigada @dilowagner  deu certo, e me desculpe o incomodo!

**Comment by dilowagner** [comment]
Que legal! 

Que isso... estamos aqui pra se ajudar...
Bons estudos!
