### ISSUE TITLE
List of attributes

### ISSUE THREAD

**Issue by joacorob** [discovery-tecnologia/dsc-mercado-livre#3]
Its possible to get the value of an attribute list?

![image](https://user-images.githubusercontent.com/7756993/35531759-b7fbcb8a-0516-11e8-9386-eb7928d8533d.png)

Thanks

**Comment by dilowagner** [comment]
Hi @joacorob 
 Yes, I believe it is possible!
Where are you trying to recover it? Maybe some mapping is missing
