### ISSUE TITLE
Multiplas contas Access Token

### ISSUE THREAD

**Issue by Thav0** [discovery-tecnologia/dsc-mercado-livre#30]
Bom dia!

Agradeço desde já pela vossa contribuição para com a comunidade.
Minha intenção para com o vosso pacote será utilizar multiplas contas através da API e aceder individualmente aos dados de cada conta
Como não vi nenhum exemplo relacionado a essa função, venho vos perguntar qual o meio de o fazer
Exemplo, o cliente autoriza-me a utilizar informações da conta dele, vendas, clientes, ... e pretendo buscar essas informações de forma individual
Podem ajudar-me?

Outra questão, nao sei se devo abrir outro issue ou não, é como renovar o token de forma a nunca expirar

Cumprimentos,
Gustavo

**Comment by dilowagner** [comment]
Ola @Thav0 tudo bem!?

Então, não sei se entendi muito bem a sua duvida... mas é possivel sim. Inclusive eu utilizo em um projeto pessoal, onde cada cliente configura o seu Token e realiza a integração de Produtos de forma individual. 
Basicamente, voce precisa fazer com o seu cliente configure o APP-ID e o SECRET-ID no seu sistema e depois instanciar a $meli com essas configs

```php
$meli = new Meli('APP-ID-CLIENTE', 'SECRET-ID-CLIENTE');
$service = new AuthorizationService($meli);
```

Sobre renovar o Token... a Lib ja faz isso automaticamente. A Lib irá armazenar o access_token e o refresh_token para utilizar nas requisiçōes que necessitarão de autenticação. Ou seja, quando o access_token estiver expirado, ele será atualizado automaticamente pela Lib, utilizando o refresh_token :)

**Comment by Thav0** [comment]
Obrigado pela resposta.
Contudo irei detalhar mais minha dúvida;
A API cria-se apenas uma unica vez e sempre que algum cliente quiser autorizar o uso das suas informações para essa API irá fornecer-nos o access token, isto é
**1 API** -> **Multiplas contas autorizadas**
Quero individualmente sem a necessidade de entrar na conta de cada cliente e criar API aceder as informações dos mesmos atraves do vosso pacote é possível?

**Comment by dilowagner** [comment]
Bom, sinceramente desconheco essa funcionalidade... acredito que nao seja possivel (hoje não é possivel fazer isso pela Lib)
Cada cliente vai ter que criar a Aplicacao no Mercado Livre e depois informar o APP-ID e o SECRET-ID... para vc instanciar os dados de acordo com cada cliente
