### ISSUE TITLE
Informações da conta autorizada

### ISSUE THREAD

**Issue by Thav0** [discovery-tecnologia/dsc-mercado-livre#31]
Bom dia!

Como obtenho os dados do cliente que autorizou a API?
Quero que após o cliente autorizar e ser direcionado para o URl eu consiga obter a informação daquele cliente em especifico ao invés de utilizar esta class :
Desc\Mercadolivre\Reresources\Users\UserService
getInformationAuthenticatedUser()

Outra questão, as informações não vêm em array, como faço para transformar o resultado?

Cumprimentos.

**Comment by dilowagner** [comment]
Pra recuperar os dados do usuario logado vc precisa utilizar esse metodo mesmo...
**Lembrando**: Voce precisa autenticar/autorizar o usuario no Mercado Livre antes

```php
$service = new UserService($meli);
$user = $service->getInformationAuthenticatedUser();
```

Outro detalhe e que esta Lib foi desenvolvida utilizando os conceitos de Orientacao a Objetos, portando ela sempre vai retornar Objetos... 
Mas se vc quiser converter pra Array, vc poderia utilizar da seguinte forma

```php
$service = new UserService($meli);
$user = $service->getInformationAuthenticatedUser();

$serializer = JMS\Serializer\SerializerBuilder::create()->build();
$json = $serializer->serialize($user, 'json');
var_dump(json_decode($json, true));
```
Esta lib ja tem a dependencia da SerializerBuilder...
Voce poderia criar uma classe de "deserializacao" do seu lado e converter o resultado

**Comment by Thav0** [comment]
Boa tarde Wagner
Obrigado pela resposta e pela atenção
Esse metodo **getInformationAuthenticatedUser()** retorna apenas um usuário,
por mais que eu dê autorização noutras contas obtenho apenas o usuário da API criada
Eu preciso obter os dados de cada conta que me der autorização da API

Cumprimentos

**Comment by dilowagner** [comment]
Entao,
Acho que nesse caso vc esta tendo um problema de Design...
Voce nao vai conseguir pegar a informacao de outras contas... apenas uma a uma...

A API do Mercado Livre eh assim... so se vc fizer um controle do seu lado...

**Comment by Thav0** [comment]
Eu fiz um teste com este pacote https://github.com/docta/mercadolibre
O que acontece aqui é o seguinte, o cliente autoriza, recebo o codigo de autorização, gero o acess token e através dele especificamente obtenho a informação da conta autorizada, podendo utilizando qualquer access token posteriormente para requisições autorizadas

Contudo o teu pacote é bem mais completo, tem o refresh token automatico entre outras funcionalidades, a unica coisa que preciso é obter informações das contas autorizadas

Wagner, tens skype ou algum outro meio de comunicação?

Cumprimentos.

**Comment by dilowagner** [comment]
Qual PATH vc utilizou? 

Usando a lib do Docta, foi essa?
```bash
/users/me
```
Talvez a API do Mercado Livre mudou... e isso nao esta implementado aqui ainda

**Comment by Thav0** [comment]
Essa mesmo, passo o token que foi gerado no url e consigo obter as informações espefificas da conta autorizada

**Comment by dilowagner** [comment]
Bom,
Nesse pacote voce nao precisa passar o Token na URL, ele ja faz isso internamente...

Faz esse teste...
**_Primeiro_**: na sua conta criada, habilite a opcao **Scope offline access**. Para nao precisar fazer todo o fluxo de Autorizacao OAuth... essa config e utilizada quando vc precisa rodar um script background (por exemplo em uma crontab)

E crie um arquivo teste.php e adicione:

```php
<?php
include 'vendor/autoload.php';

use Dsc\MercadoLivre\Meli;
use Dsc\MercadoLivre\Resources\Authorization\AuthorizationService;
use Dsc\MercadoLivre\Resources\User\UserService;

$meli = new Meli('APP-ID', 'SECRET-ID');
$service = new AuthorizationService($meli);
$service->getAccessToken();

$userService = new UserService($meli);
// Consulta dados do usuário
$user = $userService->getInformationAuthenticatedUser();

$serializer = JMS\Serializer\SerializerBuilder::create()->build();
$json = $serializer->serialize($user, 'json');
var_dump(json_decode($json, true));
```
Ve se isso nao retorna pra vc os dados do Usuario logado...
