### ISSUE TITLE
Inserir Atributos de Categoria

### ISSUE THREAD

**Issue by dilowagner** [discovery-tecnologia/dsc-mercado-livre#35]
@dilowagner, tudo bem.
Poderia dar um exemplo de como adicionar os atributos de uma categoria no momento da publicação do produto. Encontrei apenas para variação.

```php
$attributeCombination = new AttributeCombination();
// E necessario selecionar os atributos da Categoria e setar no AttributeCombination

// Primeira variacao
$variation = new Variation();
$variation->setPrice(120);
$variation->setAvailableQuantity(10);
$variation->addAttributeCombination($attributeCombination);
$variation->setPictureIds([
    'http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg'
]);

$item->addVariation($variation);
```

_Originally posted by @ombrodrigo in https://github.com/discovery-tecnologia/dsc-mercado-livre/issues/16#issuecomment-558569873_

**Comment by dilowagner** [comment]
Opa @ombrodrigo
Abri outra Issue aqui...
Vou criar um exemplo...

**Comment by dilowagner** [comment]
@ombrodrigo basicamente, vc precisa consultar antes os atributos da Categoria (com o ID da Categoria)

```php
<?php
// Consideramos que já existe um autoloader compatível com a PSR-4 registrado

// DEMAIS use`s
use Dsc\MercadoLivre\Requests\Category\CategoryService;

// E NECESSARIO ESTAR AUTENTICADO...

$meli = new Meli('APP-ID', 'SECRET-ID');

$item = new Item();
$item->setTitle('Test item - no offer')
     ->setCategoryId('ID-CATEGORIA');

// Consulta os atributos de uma determinada categoria
$service = new CategoryService();
$attributes = $service->findCategoryAttributes('ID-CATEGORIA');

$item->setAttributes($attributes);
```

**Comment by ombrodrigo** [comment]
Muito obrigado.

**Comment by diegodario88** [comment]
Olá, sobre os attributes como eu deveria preenche-los no caso do erro abaixo?

```
"Couldn't obtain a valid item condition mapping from ITEM_CONDITION attribute. Please provide a value_id.",
"error":"item.attributes.condition.invalid"
```

Alguns atributos são obrigatórios para determinadas categorias, eu deveria buscá-los antes, correto? E com essa informação em mãos montar inputs dinamicamente para que seja preenchidos e na hora da criação do anúncio suprir com o que foi informado?

**Comment by dilowagner** [comment]
Isso mesmo @diegodario88 
Talvez, vc precise exibir as Categorias para o seu usuário...
E depois que ele selecionar determinada Categoria...
Vc exibiria outro Input Select para ele selecionar os Atributos de acordo com a Categoria selecionada

**Comment by diegodario88** [comment]
Certo, por gentileza se você puder me ajudar, 
Eu tenho um json com todas os attributes que contenham a tag required da categoria que foi selecionada.
Salvei eles com o Id e o value, mas alguns são listas, que como você comentou viraram select para que o usuário selecione,
então após feito a seleção eu salvei esses atributos como:
Os que eram lista:
```
BRAND 
   {
        "id": "7636991",
        "name": "Sandisk"
   },
```

Os que eram texto:
```
{
    "id": "DATA_STORAGE_CAPACITY",
    "value": "16GB",
},

```
 Pois bem, minha dúvida é como atribuir esses valores a classe attribute?
Iniciei da seguinte forma:
```
$service = new CategoryService();
$attributes = $service->findCategoryAttributes($item->getDepartment());

$requiredAttributes = $attributes->filter(function ($element) {
     $tag = $element->getTags();   
            if ($tag->isRequired()) {
                return $element;
            }
});

//TODO: Fazer os atributos que são obrigatórios e estão em json serem aplicados aqui
 $product->setAttributes($requiredAttributes);
```

Os attributes que são lista  assim como os que são apenas id e value, eu os aplicaria da mesma forma?
Ele aceitaria um setValueType e um  setValueName, ou eu preciso tratar melhor os dados antes de passar?

**Comment by diegodario88** [comment]
@dilowagner  Estou um pouco confuso com relação ao attributes ainda, por exemplo os attributes que são do tipo string eu apenas seto o valueName dele e os que são do tipo Lista eu preciso setar o valueName e o valueId?

**Comment by dilowagner** [comment]
Eh bem complexo essa parte de Atributos mesmo kkkkk
Pela DOC quando o `value_type` for `list`, vc pode enviar na chave `values`, que aqui na lib esta mapeado por uma Collection da classe AtributeValue

https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/master/src/Requests/Category/Attribute.php#L67

Exemplo da DOC
```json
{
   "id": "COLOR",
   "name": "Color",
   "tags": {
     "allow_variations": true,
     "hidden": true
   },
   "type": "color",
   "value_type": "list",
   "values": [
     {
       "id": "52049",
       "name": "Negro",
       "metadata": {
         "rgb": "000000"
       }
     },
     {
       "id": "51993",
       "name": "Rojo",
       "metadata": {
         "rgb": "FF0000"
       }
     }
   ],
   "attribute_group_id": "DFLT",
   "attribute_group_name": "Otros"
 },
```

https://developers.mercadolivre.com.br/pt_br/atributos
