### ISSUE TITLE
Example of: refresh token

### ISSUE THREAD

**Issue by joacorob** [discovery-tecnologia/dsc-mercado-livre#4]
Hi! Could you give me some example about the best way to refresh token? thanks!

**Comment by dilowagner** [comment]
Hi @joacorob !
This is updated automatically. The library stores the access_token and refresh_token in the AccessToken object, when the request is called, it checks if the access_token is expired. If the access_token has been expired, it will be is updated with refresh_token.

Do you have any problem with this?

**Comment by joacorob** [comment]
![image](https://user-images.githubusercontent.com/7756993/36179714-29bd9802-10fc-11e8-810d-77a4321191c8.png)

Yes, but probably is because im in a local enviroment, so when y turn off my server the storage are missing? is probably?

**Comment by dilowagner** [comment]
Yes, probably...

Are you using http://localhost?

When I was testing, I also had these problems. I had that to configure a https:// address valid for my server for test this. 

When you create your App on Mercado Livre, you need to add a URL for callback. The field is called "Redirect URI" and a valid https:// address must be given. It is to this address that CODE will be sent that the lib will retrieve and send back to the Mercado Livre to get the ACCESS_TOKEN.

Honestly, I find this kind of annoying. At least as far as I know, we could not test localhost.

**Comment by joacorob** [comment]
Perfect, i didnt config https in local, so i will test other enviroment. Thanks!
