### ISSUE TITLE
Help nos atributos

### ISSUE THREAD

**Issue by dilowagner** [discovery-tecnologia/dsc-mercado-livre#52]
Opa poderia dar mais uma força nos atributos?

eu fiz conforme o exemplo mas ele me retorna uma erro.

```php 
$service = (new CategoryService())->findCategoryAttributes($data['id']);
$item->setAttributes($service);
```

erro:
```json
"message":"Couldn't obtain a valid item condition mapping from ITEM_CONDITION attribute. Please provide a value_id.",
    "error":"item.attributes.condition.invalid",
    "status":400,
    "cause":[]
```

_Originally posted by @SecDet65 in https://github.com/discovery-tecnologia/dsc-mercado-livre/issues/16#issuecomment-662616736_

**Comment by dilowagner** [comment]
@SecDet65

Estou abrindo essa Issue para não popular a outra com outros assuntos.... hehe

o valor do $data['id'] está correto?

Consegue colocar aqui como vc está criando o Item (remove os dados sensíveis)

**Comment by pablosousa7** [comment]
blz :D,

eu consegui fazer dessa forma, não sei se e o jeito certo de fazer

 ```php
$lists = [
                    'Marca' => $prod->product_name,
                    'Modelo' => $prod->product_model,
                ];

                foreach ($lists as $list => $value){
                    $attribute = new Attribute();
                    $attribute->setName($list);
                    $attribute->setValueName($value);
                    $item->addAttribute($attribute);
                }
```

Mas essa logica tem um problema, porque os atributos varia de acordo com a categoria. Estou tentando ver outra forma.

**Comment by dilowagner** [comment]
Realmente... sinceramente nao sei o seu caso de uso...
Mas acredito que vc precisa ter uma forma de listar as categorias e buscar os seus respectivos atributos em seguida...
