### ISSUE TITLE
Fluxo Authorize

### ISSUE THREAD

**Issue by diegodario88** [discovery-tecnologia/dsc-mercado-livre#54]
Olá, gostaria primeiro lhe agradecer pelo bom trabalho feito nessa lib, muito obrigado por disponibilizá-la;
Um comportamento estranho ocorreu comigo, após finalizado o fluxo  do `AuthorizationService->authorize()` as informações do `AccessToken` deveriam ficar gravadas em minha sessão, o que ocorreu em algumas situações iniciais; Porem não mais, para que isso ocorra eu tenho que chamar o  `AuthorizationService->getAccessToken()`, e o que me chamou atenção porque ele está presente no fluxo `Authorize`. (dsc.meli.refresh_token está vazio em minha sessão)

Teria alguma sugestão do porquê isso estaria acontecendo comigo?

**Comment by dilowagner** [comment]
Opa @diegodario88 obrigado pelo feedback meu caro... e desculpa pela demora na resposta, ta bem corrido hehe...
Cara, bem estranho... 
Vc esta usando qual versao de PHP?

Por acaso , vc chegou a testar com a `CacheFilesystem` e viu se aconteceu o mesmo problema?
Ex:

```php
use Dsc\MercadoLivre\Parser\ParserSerializer;
use Dsc\MercadoLivre\Storage\CacheFilesystem;
use Dsc\MercadoLivre\Configuration;
use Dsc\MercadoLivre\Environments\Production;

....

$serializer = new ParserSerializer();
$storage   = new CacheFilesystem(); // cache storage, nao usa session

$config = new Configuration($serializer, $storage);
$enviroment = new Production(Site::BRASIL, $config);

$meli = new Meli('APP-ID', 'SECRET-ID', $enviroment);

// resto do codigo...
```

**Comment by diegodario88** [comment]
Então eu tentei assim,
```
        $serializer = new ParserSerializer();
        $storage = new CacheFilesystem(WRITEPATH . 'cache/');
        $config = new Configuration($serializer, $storage);
       
        $environment  = new Production(Site::BRASIL, $config);
        $MELI = new Meli(env('APP_ID'), env('SECRET_KEY'), $environment);

        $authorization = new AuthorizationService($MELI);

        if($code) {
            return $authorization->authorize($code, $this->REDIRECT_URI);
         }
```
mas entrou em um loop infinito e levantou uma exceção 
`CRITICAL ---> Maximum function nesting level of '512' reached, aborting!`
Ele ficou tentando aqui `CacheFilesystem->set('token', 'APP_USR-...')`

**Comment by dilowagner** [comment]
@diegodario88 
Nossa! tem um bug nessa classe....
Ela esta chamando o mesmo `$this->set()` vou corrigir isso....

Qual a versao de PHP vc esta usando?

**Comment by diegodario88** [comment]
Desculpa acabei não respondendo, versão 7.4

**Comment by dilowagner** [comment]
humm, podemos ter um problema com relação a versão de PHP aí...
Preciso verificar como ele está tratando a Session nesse caso...

Essa lib está com suporte a PHP 5.6 ainda hehe, gostaria de atualizar ela em um futuro próximo :(

Mas só confirmando, vc disse que está usando as duas abordagens... é isso?
`AuthorizationService->authorize()`
`AuthorizationService->getAccessToken()`

Eu acredito que em algum momento pela lógica da sua aplicação... uma pode estar sobreescrevendo a outra

O fluxo do `authorize` seria utilizado mais para ter a interação com o usuário final e criar um tela para ele permitir que a aplicação tenha acesso (Fluxo de OAuth2)

Já o `getAccessToken` seria mais utilizado onde não necessitamos de uma interação com o usuário, por exemplo... em algum script de background que faz a consulta e importação de dados (Script de CRON) - com o Scope Offline habilitado...

**Comment by diegodario88** [comment]
No caso se eu deixar acontecer o fluxo do AuthorizationService->authorize() ele não grava as informações na session. Ai uma manobra que  eu testei foi invocar o AuthorizationService->getAccessToken() para ter essas informações.

Uma coisa que verifiquei foi que o meu storage está com sessionId nulo mas o prefix está  "dsc.meli."

` $this->MELI->environment->*Dsc\MercadoLivre\Environment*configuration->storage->sessionId`

**Acabei encontrando o problema e era com o método session(). É um global que por algum motivo estava interferindo 😬
AEEeee!

**Comment by dilowagner** [comment]
@diegodario88 
Opa, agora que vi sua mensagem anterior hehe... 
Resolveu entao??? kkk era uma chamada da funcao session() na sua aplicacao?

Mas mesmo assim, criei uma versao de correcao da CacheFilesystem
[Versao 1.14.1](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/1.14.1)

Valeuuuss

**Comment by diegodario88** [comment]
Exatamente, era um ` session()` lá no meio do nada hahaha.

**Comment by dilowagner** [comment]
Há blzzz @diegodario88 
Valeuus
