### ISSUE TITLE
Versao do Guzzle

### ISSUE THREAD

**Issue by rafa-acioly** [discovery-tecnologia/dsc-mercado-livre#56]
Podemos colocar a versao do `Guzzle` para `^6.*`? assim nao teremos problema de compatibilidade para aplicacoes que usam `php7.x`.

No meu caso, estou usando o `php7.4` com a versao `^7.x` do guzzle (aplicacao laravel) e isso esta gerando o erro:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dsc/mercado-livre 1.14.1 requires guzzlehttp/guzzle 6.3.3 -> satisfiable by guzzlehttp/guzzle[6.3.3] but these conflict with your requirements or minimum-stability.
    - dsc/mercado-livre 1.14.0 requires guzzlehttp/guzzle 6.3.3 -> satisfiable by guzzlehttp/guzzle[6.3.3] but these conflict with your requirements or minimum-stability.
    - Installation request for dsc/mercado-livre ^1.14 -> satisfiable by dsc/mercado-livre[1.14.0, 1.14.1].
```

> https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/master/composer.json#L23

**Comment by dilowagner** [comment]
Opa, @rafa-acioly sinceramente, tenho que avaliar se isso nao pode quebrar a compatibilidade com o pessoal que ainda usa o PHP5.6

**Comment by rafa-acioly** [comment]
@dilowagner acho que seria melhor criar uma tag para dar suporte a versao `5.6` e mover o projeto para a versao `7` o que acha?
assim podemos deixar claro no `readme` que a versao `5.6` esta em uma tag especifica.

Aproveitando a thread para uma duvida:

'e possivel publicar/alterar os produtos de um seller especifico? hoje para isso acontecer a gente precisa fazer a chamada no `oauth` e pegar o `code`, como poderiamos fazer para atualizar um produto de um `seller` especifico (que ja instalou um app na conta) em background?

**Comment by gabrielmoura** [comment]
Seria de grande utilidade para integração com laravel eu outros frameworks.

**Comment by rafa-acioly** [comment]
exatamente @gabrielmoura, a maioria dos frameworks e libs ja miram como requerimento minimo o php7, no meu caso 'e justamente o laravel.

**Comment by dilowagner** [comment]
Opa, legal mesmo...
Acho que vou fechar a versao 1.* pra isso

E criar uma versao 2.0.0-rc para migracao do PHP 7+

@rafa-acioly consegue criar um Pull Request com essa mudanca do Composer?
E cara sobre a pergunta do `Seller` especifico, acho que isso nao foi criado ainda... terias um exemplo do JSON enviado?

**Comment by rafa-acioly** [comment]
@dilowagner abri o PR #58 

Com relacao ao JSON enviado, eu nao tenho nenhum dado enviado, so gostaria de saber como podemos fazer para pegar um token de um usuario especifico sem passar pelo `oauth` do navegador.

**Comment by dilowagner** [comment]
Show de bola @rafa-acioly, obrigado pelo PR hehe
 
Há, e vc consegue com o método `$service->getAccessToken()` do `AuthorizationService()`
https://github.com/discovery-tecnologia/dsc-mercado-livre#exemplo-de-autentica%C3%A7%C3%A3o-server-side

Mas pra isso vc precisa habilitar na integração o **Scope offline access** lá no Painel do Mercado Livre

**Comment by dilowagner** [comment]
@rafa-acioly 
Esqueci de atualizar o README hehe
Mas a versão foi criada: [2.0.0-rc](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/2.0.0-rc)
