### ISSUE TITLE
 Link para autenticação

### ISSUE THREAD

**Issue by diegodario88** [discovery-tecnologia/dsc-mercado-livre#61]
Dês de ontem, dia 15/10/20, não consigo mais autenticar o meu aplicativo. Seria um problema apenas comigo?
Aparentemente a auth url do BR está offline -> `https://auth.mercadolivre.com.br`

Error:
```
Não é possível acessar esse site
A página https://auth.mercadolivre.com.br/authorization?client_id=${MeuId}&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth 
pode estar temporariamente indisponível ou pode ter sido movida permanentemente para um novo endereço da Web.
ERR_INVALID_RESPONSE
```
Pelo que eu vi o auth URL da Argentina esta funcionando normal.

**Comment by dilowagner** [comment]
Fala @diegodario88 blz...
Cara, parece que deve ter acontecido alguma indisponibilidade momentanea (ainda nao esta funcionando?)... nao encontrei nada que informa alguma mudanca na URL...
Inclusive esta sendo referenciado na SDK Oficial deles

https://github.com/mercadolibre/php-sdk#usage

**Comment by diegodario88** [comment]
Então @dilowagner ainda não esta funcionando, estranho né. Eu abri uma issue no repo do sdk talvez alguém saiba de alguma coisa lá...

EDIT: Testei com o url do argentina e realmente esse funciona mas como é outro site não consigo usar meu projeto. 

EDIT: Por algum motivo obscuro voltou a funcionar mas apenas no firefox, no chrome continua aparecendo esse erro. Vou tentar limpar o cache e resetar as configurações.
