### ISSUE TITLE
Ajuda com notificações

### ISSUE THREAD

**Issue by diegodario88** [discovery-tecnologia/dsc-mercado-livre#63]
@dilowagner  Por gentileza, gostaria de pedir um auxílio a você, estou inscrito nas notificações de orders e baseado nelas faço atualização da minha base de dados. Porem chegam 5 notificações para cada compra, todas elas com o mesmo ID e o status de paid. Como faço para que apenas uma baixa de estoque seja feita? Isso foge do escopo da lib e vai mais para a parte da documentação mas eu realmente não consegui entender o porquê desse comportamento.

**Comment by dilowagner** [comment]
Opa e ai @diegodario88 
Nao sei se entendi completamente, sua duvida, mas esta chegando repetido os eventos? 

Eh estranho esse comportamento, mas sera que vc nao esta enviando mais de uma vez algo que dispare as notificacoes?

E se esse envio eh feito por eles mesmo...(nao fica do nosso lado), acredito que a unica forma eh vc criar uma especie de controle do seu lado para nao repetir o processamento....

**Comment by diegodario88** [comment]
É exatamente isso. Para 1 venda chegam 5 notificações com o mesmo id e o status de paid. Mas eu troquei a inscrição para payments lá no app e agora parece que vem apenas uma. Acredito que faz parte do fluxo do created_orders, não sei...hehe

**Comment by diegodario88** [comment]
Mudei a inscrição para payments porque eu só gostaria de controlar o estoque então só preciso da notificação da venda para atualizar a base. Blz, faço uma compra usando o usuário teste e um cartão de teste, chega uma notificação assim:
```
{
	"resource":"/collections/12121420815",
         "user_id":149712345,
	"topic":"payments",
	"application_id":1163634307212345,
	"attempts":1,
	"sent":"2020-10-30T19:11:39.678Z",
	"received":"2020-10-30T19:11:39.656Z"
}
```

Eu pego aquele código no final do resource e passo para o `$service->findPayment($code);`

Deveria me retornar o pagamento, mas ele volta dizendo:

```
{
  "message": "Payment not found",
  "error": "not_found",
  "status": 404,
  "cause": {
    "code": 2000,
    "description": "Payment not found",
    "data": null
  }
}
```
O que eu estou esquecendo aqui?

*Detalhe que localmente funciona normal, ou seja ele encontra o pagamento.

**Comment by dilowagner** [comment]
Opa e ai @diegodario88 
Cara, sinceramente nunca avancei nesse nivel de implementacao no ML hehe. Ao primeiro momento parece estranho voce ter que capturar o final do `resource` ali. Vc recebe apenas essa estrutura de JSON?
Terias o link do trecho da DOC do ML, pode ser que seja outro metodo que ainda nao estava mapeado na Lib. (so acho estranho no local funcionar hehe)

**Comment by diegodario88** [comment]
Sim, recebo apenas aquele json. Eu consegui buscar a notificação usando o findPaymentsOfSeller.

Então acabei de descobrir que na verdade era por causa do token. Api poderia me retornar informando que o token estava inválido ou alguma coisa nesse sentido né. 😒

Obrigado pelo retorno

**Comment by dilowagner** [comment]
Opa, blzzz hehe
Mas quando vc fala API, eh o backend mesmo correto? Ou algo na Lib que nao esta passando a informacao corretamente pra frente (alguma Exception por exemplo)?

**Comment by diegodario88** [comment]
Não, é o backend mesmo isso ocorre usando o postman ou insomnia .
