### ISSUE TITLE
Erro ["item.official_store_id","item.seller_id"]

### ISSUE THREAD

**Issue by christopherpersaud** [discovery-tecnologia/dsc-mercado-livre#64]
Na hora de enviar o anuncio da o erro: ["item.official_store_id","item.seller_id"]
mas os itens nao tem marca mesmo nao, e o cadastro do mercado livre nao tem loja oficial vinculada nem marca vinculada, como resolver esse erro? sabem me dizer?

Código de envio:
$item = new Item();
      		$item->setTitle('Velas de enfeite')
      			->setCategoryId('MLB31547')
      			->setPrice(100)
      			->setCurrencyId('BRL')
      			->setAvailableQuantity(10)
      			->setBuyingMode('buy_it_now')
      			->setListingTypeId('gold_special')
      			->setCondition('new')
      			->setDescription('Descricao do produto');
      
      		$picture = new Picture();
      		$picture->setSource('http://mla-s2-p.mlstatic.com/968521-MLA20805195516_072016-O.jpg');
      		$item->addPicture($picture);
      
      		$announcement = new Announcement($meli);

**Comment by dilowagner** [comment]
Cara, parece ser algo com a sua conta mesmo @christopherpersaud eh uma conta de teste?
E parece ser algo configurado pelo proprio Mercado Livre

https://developers.mercadolivre.com.br/pt_br/lojas-oficiais#Erros
"entre em contato com um consultor comercial"

**Comment by christopherpersaud** [comment]
Não é conta de teste é de uma concessionaria, mas nao tem nenhuma marca ou loja oficial vinculada a ela, como se houvesse algum tipo de dado incompleto na conta, mas to vendo isso junto ao cliente.
Achava que poderia ser alguma coisa com o codigo, mas é na conta mesmo, obrigado mais uma vez
