### ISSUE TITLE
SDKs deprecados, evite ficar bloqueado!

### ISSUE THREAD

**Issue by rabraga** [discovery-tecnologia/dsc-mercado-livre#65]
Boas!
Recebi um e-mail do openplatform@mercadolivre.com com o seguinte conteúdo abaixo. O que isso quer dizer? O mercado livre vai bloquear esta biblioteca dsc-mercado-livre? 
--
A partir de 31 de dezembro as integrações que usarem SDKs antigos serão bloqueadas ao fazerem chamadas aos recursos do Mercado Livre 

Identificamos   que você segue usando um SDKs deprecado e logo ele será bloqueado.       Atualize a sua aplicação com as libraries recomendadas disponíveis em nossas   ferramentas, evitando que suas chamadas à API do Mercado Livre sejam   bloqueadas, por uso de SDKs deprecados.      Consulte também o Desenvolvimento   Seguro com boas práticas.
--

**Comment by dilowagner** [comment]
Eitaaaa, como assim??? Nao lembro de ter recebido esse e-mail!!! Mas aparentemente sim!
Consegues fazer um teste rapido pra gente?

Alterar o Header
https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/bc6a90401d4f09f937233130f24ba679a424d751/src/Client.php#L25
MELI-PHP-SDK-1.1.0

Para:
https://github.com/mercadolibre/php-sdk/blob/958cb910810efee6299f27b233881f26b3f9b667/lib/Configuration.php#L91
MELI-PHP-SDK-3.0.0 

Ou outro nome mesmo, algo do tipo: MELI-DSC-SDK
E verificar se continua funcionando? Pretendo testar tambem

Pode ser que eles so estejam validando esse Header

Gostaria de atualizar esse projeto, mas sozinho ta dificil e ando sem tempo :(

**Comment by rabraga** [comment]
@dilowagner ,
Eu baixei este projeto semana passada, e comecei a testar. Nesta segunda 30/11 recebi este e-mail. Será que eles irão aceitar somente as SDK indicadas no link: https://developers.mercadolivre.com.br/pt_br/ferramentas ???

Fiz um teste usando MELI-PHP-SDK-3.0.0, e consegui gerar o Token e criar um anuncio de teste. Acredito que seja esta alteração mesmo de User-Agent que deve estar sendo validada, já que você estava usando a mesma da SDK recomendada por eles. 

Mas vamos saber só dia 01/01/2021.

Estou disposto a ajudar e contribuir com o projeto.

**Comment by dilowagner** [comment]
Valeu @rabraga obrigado!
Vc conseguiria testar com MELI-DSC-SDK e verificar se existe algum bloqueio? Acredito que seria até o mais certo talvez, pra não ficar mascarando o uso da Lib deles, seilá.

Bom e esperamos que sim, vou ver pra atualizar isso o quanto antes....

Legal que vc queira contribuir, minha ideia é evoluir para os recursos atuais do PHP 7+ (ou 8 agora talvez hehe).

E se vc achar interessante, pode gerar uma PR dessa alteração pra gente...
Valeuuus!

**Comment by rabraga** [comment]
@dilowagner ,
Criei o PR, já testei com MELI-DSC-SDK e deu certo. Certamente estavam identificando que a MELI-PHP-SDK-1.1.0 está desatualizada. Acredito que não irá bloquear a MELI-DSC-SDK.

Eu estou utilizando o PHP 7.4. Até agora gerei o token e criei um anuncio de teste, com o AnnouncementTest.php, apenas retirando o ->setWarranty('12 months').

**Comment by dilowagner** [comment]
Valeu @rabraga 
Obrigado pela ajuda...
Vou gerar uma versão

**Comment by dilowagner** [comment]
[Versão 2.0.1-rc](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/2.0.1-rc)
