### ISSUE TITLE
A partir de 1º de abril será obrigatório o envio do access token no header das chamadas a nossa API

### ISSUE THREAD

**Issue by rabraga** [discovery-tecnologia/dsc-mercado-livre#67]
Bom dia!
Recebi este e-mail:
--
Atualize   todas as suas chamadas com access token no header, por exemplo:       

curl   -X GET -H 'Authorization: Bearer $ACCESS_TOKEN'   https://api.mercadolibre.com/items/$ITEM_ID       

Caso não o envie, receberá um erro.
--

**Comment by diegodario88** [comment]
![mlAlert](https://user-images.githubusercontent.com/25825145/104321105-f160b400-54c1-11eb-9b81-17052bf81bff.jpeg)

É eu também recebi, no caso acredito que teria que atualizar o default headers. 


![Captura de tela de 2021-01-12 10-38-54](https://user-images.githubusercontent.com/25825145/104321503-78159100-54c2-11eb-99ec-3c0398e37187.png)

**Comment by rabraga** [comment]
Acho que é isso mesmo, porém não consigo fazer alterações e testes nesta semana. Só na próxima.

**Comment by dilowagner** [comment]
Opa, valeu pelo report pessoal!
Vou verificar pra atualizar o quanto antes

**Comment by dilowagner** [comment]
So espero que isso nao seja mentira kkkkkkkkkkkkkkkkkk (1 de abril!)

Brinks...
Publiquei uma nova versao com o ajuste pessoal
[Versao 2.0.3-rc](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/2.0.3-rc)
