### ISSUE TITLE
Access token no cabeçalho da requisição

### ISSUE THREAD

**Issue by rafa-acioly** [discovery-tecnologia/dsc-mercado-livre#73]
A partir do dia 01-04 as requisições precisaram conter o token no header:

> https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Enviar-access-token-no-header

**Comment by rafa-acioly** [comment]
Abri um `PR` para tentar implementar essa alteração mas acredito que não seja isso ainda, porque eu precisaria verificar se o token ainda é valido antes de fazer a request 🤔 

https://github.com/discovery-tecnologia/dsc-mercado-livre/pull/74

**Comment by dilowagner** [comment]
Fala @rafa-acioly blz?
Esse ajuste ja foi implementado, a galera ja tinha reportado esse problema em outra [Issue #67](https://github.com/discovery-tecnologia/dsc-mercado-livre/issues/67) 

https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/2320cdacee6a67b5e64a275280193c0d62df3406/src/Handler/OAuth2ClientHandler.php#L88
