### ISSUE TITLE
RefreshToken para authorization codes já autenticados

### ISSUE THREAD

**Issue by fcristinadebora** [discovery-tecnologia/dsc-mercado-livre#76]
Olá!

Estou desenvolvendo integração com o ML e estou obtendo o erro abaixo ao tentar autenticar um vendedor, após ele já ter sido autenticado na minha máquina ou na de qualquer dev:
```javascript
{
    "error_message": "[400] Some errors occurred: {\"message\":\"Error validating grant. Your authorization code or refresh token may be expired or it was already used\",\"error\":\"invalid_grant\",\"status\":400,\"cause\":[]}",
    "error_file": "/var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/MeliException.php",
    "error_line": 25,
    "error_trace": "#0 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Client.php(60): Dsc\\MercadoLivre\\MeliException::create(Object(GuzzleHttp\\Psr7\\Response))\n#1 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Client.php(118): Dsc\\MercadoLivre\\Client->handleError(Object(GuzzleHttp\\Exception\\ClientException))\n#2 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Client.php(71): Dsc\\MercadoLivre\\Client->execute('POST', '/oauth/token', Array)\n#3 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/BaseService.php(64): Dsc\\MercadoLivre\\Client->post('/oauth/token', '{\"grant_type\":\"...', Array)\n#4 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Resources/Authorization/AuthorizationService.php(108): Dsc\\MercadoLivre\\BaseService->post('/oauth/token', Array, Array)\n#5 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Resources/Authorization/AuthorizationService.php(77): Dsc\\MercadoLivre\\Resources\\Authorization\\AuthorizationService->getToken(Array)\n#6 /var/www/html/clipp/Backend/module/Inventory/src/Inventory/Service/MercadoLivre/MLB.php(67): Dsc\\MercadoLivre\\Resources\\Authorization\\AuthorizationService->authorize('TG-605e2a2ef734...', 'https://clippfa...')\n#7 /var/www/html/clipp/Backend/module/Inventory/src/Inventory/Service/MercadoLivre/Authentication.php(40): Inventory\\Service\\MercadoLivre\\MLB->authorize('TG-605e2a2ef734...', Object(Application\\Model\\Client))\n#8 /var/www/html/clipp/Backend/public/index.php(85): Inventory\\Service\\MercadoLivre\\Authentication->authorize(Object(Core\\Service\\ParameterSet), Array)\n#9 {main}",
    "error_code": 0
}
```

O erro ocorre justamente pelo fato do token já ter sido utilizado, pois se eu atualizar o token, conforme a documentação: https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao#Refresh-token
Obtenho o novo token:
![image](https://user-images.githubusercontent.com/17615066/112690231-33ab5780-8e5a-11eb-8142-c624909a19f6.png)

Pensei em basicamente, caso obter erro de autenticação tentar chamar o endpoint para atualização do token. Há algum método específico para fazer isso, sem ele necessariamente estar expirado?

Versão da lib utilizada: 2.1.0-rc
Meu código: 
![image](https://user-images.githubusercontent.com/17615066/112690381-6d7c5e00-8e5a-11eb-894a-107e1445188a.png)

**Comment by dilowagner** [comment]
Ola @fcristinadebora obrigado por reportar...
Entao, a lib ja deveria fazer isso...

Na classe `OAuth2ClientHandler` - ela verifica se o token ja esta expirado
https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/d175b7bc6342891e15ab9894c20df1652edf446b/src/Handler/OAuth2ClientHandler.php#L73

E da um refresh
https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/d175b7bc6342891e15ab9894c20df1652edf446b/src/Handler/OAuth2ClientHandler.php#L75

Mas pelo que entendi podemos estar com um problema que o @rafa-acioly relatou na Issue #72 

Voce esta usando usuarios diferente pra mesma conta? tipo, para a mesma `APP-ID`?

**Comment by fcristinadebora** [comment]
Bom dia! Obrigada pelo retorno rápido.

Sim, a ideia é que minha aplicação com N usuários, cada qual com sua conta no ML, autorizem a minha APP-ID. 

O meu problema seria, na verdade, relacionado à tentativa de "reautenticação" antes do token expirar, porém hoje fui testar a autenticação com um token já expirado (teoricamente após 6h o token deve expirar) e obtive o mesmo problema. Segue exception obtida:

```json
{
    "error_message": "[400] Some errors occurred: {\"message\":\"Error validating grant. Your authorization code or refresh token may be expired or it was already used\",\"error\":\"invalid_grant\",\"status\":400,\"cause\":[]}",
    "error_file": "/var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/MeliException.php",
    "error_line": 25,
    "error_trace": "#0 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Client.php(60): Dsc\\MercadoLivre\\MeliException::create(Object(GuzzleHttp\\Psr7\\Response))\n#1 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Client.php(118): Dsc\\MercadoLivre\\Client->handleError(Object(GuzzleHttp\\Exception\\ClientException))\n#2 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Client.php(71): Dsc\\MercadoLivre\\Client->execute('POST', '/oauth/token', Array)\n#3 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/BaseService.php(64): Dsc\\MercadoLivre\\Client->post('/oauth/token', '{\"grant_type\":\"...', Array)\n#4 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Resources/Authorization/AuthorizationService.php(108): Dsc\\MercadoLivre\\BaseService->post('/oauth/token', Array, Array)\n#5 /var/www/html/clipp/Backend/vendor/dsc/mercado-livre/src/Resources/Authorization/AuthorizationService.php(77): Dsc\\MercadoLivre\\Resources\\Authorization\\AuthorizationService->getToken(Array)\n#6 /var/www/html/clipp/Backend/module/Inventory/src/Inventory/Service/MercadoLivre/MLB.php(67): Dsc\\MercadoLivre\\Resources\\Authorization\\AuthorizationService->authorize('TG-605e2a2ef734...', 'https://clippfa...')\n#7 /var/www/html/clipp/Backend/module/Inventory/src/Inventory/Service/MercadoLivre/Authentication.php(41): Inventory\\Service\\MercadoLivre\\MLB->authorize('TG-605e2a2ef734...', Object(Application\\Model\\Client))\n#8 /var/www/html/clipp/Backend/public/index.php(85): Inventory\\Service\\MercadoLivre\\Authentication->authorize(Object(Core\\Service\\ParameterSet), Array)\n#9 {main}",
    "error_code": 0
}
```

**Comment by dilowagner** [comment]
@fcristinadebora 
Quando vc diz: "**cada qual com sua conta no ML**"

Cada "cliente" vai ter sua propria `APP-ID` e `SECRET-ID`? ou nao? 

Ou sao usuarios dentro da sua propria Aplicacao? Todos usuariam a mesma `APP-ID` e `SECRET-ID` - referente a sua Aplicacao. Se for, preciso analisar esse cenario.

Eu tenho um cenario onde eu uso a lib e cada cliente tem a sua Aplicacao no Mercado Livre... ou seja o cliente tem um painel onde ele insere a sua `APP-ID` e `SECRET-ID` - a partir disso ele comeca a publicar com a propria conta.

**Comment by dilowagner** [comment]
@fcristinadebora 
Vc consegue fazer um teste pra gente com a versao `dev-master`?
Eu adicionei a opcao de setar o user_id na classe `Meli`, ficaria assim:

```php
<?php

$meli = new Meli('APP-ID', 'SECRET-ID');
$meli->setUserId('USER-ID');
```

**Comment by fcristinadebora** [comment]
@dilowagner 

Testei com a alteração que vc sugeriu na `dev-master` porém o problema persiste ao tentar chamar o método `authorize`. Ao chamar o método `AuthorizationService->getAccessToken()` setando qualquer `userId` (obtido a partir da consulta à lista de grants da minha aplicação, porém pode inclusive ser um userID inválido) sempre é retornado o `acess token` referente à conta proprietária da aplicação (estou conferindo com a request https://developers.mercadolivre.com.br/pt_br/automovel-consulta-de-usuarios#Consultar-meus-dados-pessoais)

Sobre ser a mesma `APP-ID`, sim, é a mesma... Seria exatamente essse caso
"Ou sao usuarios dentro da sua propria Aplicacao? Todos usuariam a mesma APP-ID e SECRET-ID - referente a sua Aplicacao." onde cada cliente tem sua conta de vendedor no mercado livre e apenas autoriza a minha APP-ID.

**Comment by dilowagner** [comment]
@fcristinadebora 
Hum, entao nao parece ser, o que pensei que seria hehe

Vc ja deu uma olhada nesses erros?
https://developers.mercadolivre.com.br/pt_br/autenticacao-e-autorizacao?nocache=true#Erro-invalid-grant

Sinceramente, nunca peguei um cenario desses, vou ter que analisar melhor.
O mais estranho e que na minha cabeca nao deveria estar bugando, por ser a mesma `APP-ID`

**Comment by fcristinadebora** [comment]
@dilowagner 
Acabei descobrindo um workaround para isso. Quando eu já autentiquei um usuário porém não salvei seu `access token` eu não consigo mais acessar os métodos `authorization_code`autenticação nem `refresh_token`. Porém, descobri que se enviar o parâmetro state, o ML gera um novo `authorization code` que consigo utilizar para autenticar. Assim, caso obter `invalid_grant` ao tentar autenticar o usuário, apenas envio um state que ainda não tenha sido utilizado.

A lib não possuía o parâmetro state no método `getOauthUrl`, então abri o PR #78 para evitar ter que colocá-lo manualmente depois de obter a URL de autenticação através da chamada do método

**Comment by dilowagner** [comment]
Eita,
Valeu @fcristinadebora

**Comment by dilowagner** [comment]
Merged Versao [2.2.0-rc](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/2.2.0-rc)

**Comment by caiolima86** [comment]
> @dilowagner
> Acabei descobrindo um workaround para isso. Quando eu já autentiquei um usuário porém não salvei seu `access token` eu não consigo mais acessar os métodos `authorization_code`autenticação nem `refresh_token`. Porém, descobri que se enviar o parâmetro state, o ML gera um novo `authorization code` que consigo utilizar para autenticar. Assim, caso obter `invalid_grant` ao tentar autenticar o usuário, apenas envio um state que ainda não tenha sido utilizado.
> 
> A lib não possuía o parâmetro state no método `getOauthUrl`, então abri o PR #78 para evitar ter que colocá-lo manualmente depois de obter a URL de autenticação através da chamada do método


Poxa, estou tendo o mesmo problema, você consegue colocar como ficou o seu codigo?
Como vc esta fazendo para pegar o RefreshToken?, vc esta usando ele no autorize?

**Comment by fcristinadebora** [comment]
Olá @caiolima86 :)

Infelizmente não tenho mais acesso aos fontes do programa, porém a solução é simples.

O `RefreshToken` é usado para solicitar um novo `authorization_code`, através do método próprio para isso. Da forma como fiz, não preciso armazenar o `RefreshToken`, visto que todas as vezes obtenho um novo `authorization code`. 
Isso é possível graças a passagem de parâmetro no método `getOAuthUrl`:
```php
$service->getOAuthUrl('https://your-domain/login.php', 'your-state-value')
```
Em "`your-state-value`", coloquei um timestamp mesmo, ex: `date('Ymdhis')` 

O restante da autenticação era feito por fora da lib, então fora a documentação oficial não saberei te dizer como obter as credenciais.

Espero ter ajudado :)
