### ISSUE TITLE
Publicar anúncio via crontab

### ISSUE THREAD

**Issue by helquisson** [discovery-tecnologia/dsc-mercado-livre#8]
Issue referente ao pull request (question): 
https://github.com/discovery-tecnologia/dsc-mercado-livre/pull/7

Continuando...

Então, nesse caso vou mudar um pouco o escopo do projeto, vou tentar usar APPs diferentes. 
Quando finalizar, passo um feedback pra vcs.

Valew @dilowagner

**Comment by dilowagner** [comment]
Show @helquisson 

Qualquer coisa poste aqui!

Abraco!

**Comment by helquisson** [comment]
Eae @dilowagner , blz cara?

Tudo rodando lindão! Só uma coisa que to sentindo falta, ou não percebi como que faz! É a adição de atributos em produtos simples, sem variação, tipo isso:

$attribute = new Attribute();
$attribute->setName('name');
$attribute->setValueId(10);
$attribute->setValueName('test');

$item->addAttribute($attribute);
...

Ou já tem algo implementado?

Att,

**Comment by dilowagner** [comment]
Opa @helquisson 
faltou esse mapeamento mesmo... vou verificar...

**Comment by dilowagner** [comment]
Ola @helquisson 
Publiquei uma nova [release 1.6.0](https://github.com/discovery-tecnologia/dsc-mercado-livre/releases/tag/1.6.0) com esse mapeamento

**Comment by helquisson** [comment]
@dilowagner, perfeito cara, show de bola!
