### ISSUE TITLE
Atributos

### ISSUE THREAD

**Issue by Rodrigomsdevs** [discovery-tecnologia/dsc-mercado-livre#82]
Diego, nos falamos pelo linkedin.

meu problema é que estou tentando publicar um produto sem atributo.
Eu vi sobre isso no site do ml, mas nao consegui entender, se puder me ajudar agradeço. 

{
"department":"items",
"cause_id":147,
"type":"error",
"code":"item.attributes.missing_required",
"references":[
"item.attributes",
"item.variations.attribute_combinations"
],
"message":"The attributes [BRAND, MODEL, COLOR] are required for category MLB73057. Check the attribute is present in the attributes list or in all variation's attributes_combination or attributes."
},

**Comment by dilowagner** [comment]
Opa e ae @Rodrigomsdevs blz?
Cara, entao... isso é uma validacao do proprio Mercado Livre, algumas categorias é obrigatorio informar os atributos!
Nesse exemplo, essa categoria é obrigatorio informar os atributos: **Marca**, **Modelo** e **Cor**.

https://api.mercadolibre.com/categories/MLB73057/attributes

Se vc perceber, tem o atributo `tags` e o campo `required = true` no JSON

Nao sei se vc estaria desenvolvendo uma tela pra isso, mas nesse caso vc consegue recuperar os atributos da categoria, exibir para o usuario e validar os obrigatorios.

```php
$service = new CategoryService();
$attributes = $service->findCategoryAttributes($code);
```
https://github.com/discovery-tecnologia/dsc-mercado-livre/blob/master/src/Requests/Category/CategoryService.php#L43

**Comment by dilowagner** [comment]
Ola @Rodrigomsdevs 
deu certo? Conseguiu resolver?
