### ISSUE TITLE
Buscando Orders

### ISSUE THREAD

**Issue by EmersonHenriique** [discovery-tecnologia/dsc-mercado-livre#83]
Ola meus amigos, estou tentando listar as orders pela função "findOrdersBySeller" porem ela me retorna em var_dump() totalmente ilegivel, como seria possivel tratar o resultado para um formato json?
`object(Dsc\MercadoLivre\Resources\Order\OrdersList)#105 (4) { ["query":"Dsc\MercadoLivre\Resources\Order\OrdersList":private]=> string(0) "" ["display":"Dsc\MercadoLivre\Resources\Order\OrdersList":private]=> string(7) "partial" ["paging":"Dsc\MercadoLivre\Resources\Order\OrdersList":private]=> object(Dsc\MercadoLivre\Resources\Page\Paging)#115 (3) { ["total":"Dsc\MercadoLivre\Resources\Page\Paging":private]=> int(7906) ["offset":"Dsc\MercadoLivre\Resources\Page\Paging":private]=> int(0) ["limit":"Dsc\MercadoLivre\Resources\Page\Paging":private]=> int(50) } ["results":"Dsc\MercadoLivre\Resources\Order\OrdersList":private]=> object(Doctrine\Common\Collections\ArrayCollection)#117 (1) { ["elements":"Doctrine\Common\Collections\ArrayCollection":private]=> array(50) { [0]=>`

**Comment by dilowagner** [comment]
E ae @EmersonHenriique 
Foi mau a demora na resposta, mas to na correria hehe...

Ele retorna uma Collection... para transformar em um JSON vc poderia usar

```php
echo json_encode($orders);
```

Ou apenas os resultados...

```php
echo json_encode($orders->getResults());
```
