### ISSUE TITLE
Como Listar Anúncios Conta ML

### ISSUE THREAD

**Issue by caiolima86** [discovery-tecnologia/dsc-mercado-livre#84]
Primeiramente quero agradecer pela biblioteca, está sendo de grande ajuda a comunidade =)

Como faço para listar os anúncios ativos ou inativos de uma conta ml?

Pelo que vi na api, isso é feito pela url: https://api.mercadolibre.com/sites/$SITE_ID/search?seller_id=$SELLER_ID
Porém não encontrei nada referente a essa url na biblioteca.

Obrigado

**Comment by caiolima86** [comment]
Desculpe a ignorância no post anterior...rs... da para fazer a culsulta com Curl.

O problema é que o token que eu consigo gerar é o:

$meli = new Meli(MLAPPID, MLSECRETKEY);
$service = new AuthorizationService($meli);
$token = $service->getAccessToken();

Esse token é para uso do meu app... eu achei que depois de uma conta de um user do ml sendo autorizada, eu conseguiria manipular a conta dele utilizando esse token, mas percebi que não é possivel.

como faço para gerar um token de um user que ja autorizou o app apenas com php, sem que ele precise entrar no meu sistema?
aquele code gerado quando ele autorizou é valido para sempre?

Obrigado pela atenção e desculpe, sou novato na api do ml

**Comment by caiolima86** [comment]
Corrigindo a url correta que quero acessar a lista de anúncios ativos é: https://api.mercadolibre.com/users/$idContaMl/items/search

**Comment by caiolima86** [comment]
Analizando as perguntas feitas por outros usuários, notei que você pede para o nosso cliente crie um app no mercado livre para ter o seu app id e secret code, porém acho essa forma inviável, tendo em vista que os outros apps do ml como o bling, mercado busca entre outros... não precisem que o cliente crie um app novo, precisa apenas autorizar o uso do app deles e pronto.

Agradeço a atenção de vcs =)

**Comment by dilowagner** [comment]
Fala @caiolima86 blz? Obrigado e desculpa a demora... (correria) hehe
Essa tratativa apontada nessa Issue #76 nao te ajuda?

**Comment by caiolima86** [comment]
Opa, blz... obrigado pelo retorno...

Entao... eu não sei como pegar o refresh token para usar ele na:
$service->authorizeClient('code', 'url_login');

não encontrei nenhum metodo que retorne ele... so consigo pegar ele no momento que o meu cliente autoriza o meu app no ml

tentei fazer isso para logar com o id do meu cliente ja autorizado:

$meli = new Meli(MLAPPID, MLSECRETKEY);
$meli->setUserId($idContaMl);
$service = new AuthorizationService($meli);
print_r($service->getAuthorizationCode(MLREDIRECTURI));

mas retorna "User not authenticate - unauthorized"


e se eu faço isso abre a tela de login do mercado livre, sendo que esse id de usuario ja autorizou meu app no ml:

$meli = new Meli(MLAPPID, MLSECRETKEY);
$meli->setUserId($idContaMl);
$service = new AuthorizationService($meli);
$service->getAccessToken();
print_r($service->getAuthorizationCode(MLREDIRECTURI));

sinceramente ja tentei de tudo...rsrsrs... mas nao consegui autenticar um usuario que autorizou meu app...
Se você puder me dar uma luz com algum exemplo de codigo... irá ajudar muito.

Obrigado pela atenção \o/

**Comment by caiolima86** [comment]
Acabei conseguindo fazer o que queria com outra a lib: gpupo/mercadolivre-sdk
Ela me dará mais trabalho...rs... mas consigo alternar facilmente entre as contas autorizadas.

Mesmo assim, obrigado e parabéns pelo projeto, tenho ctz que esta ajudando muito a comunidade =)

**Comment by dilowagner** [comment]
Opa, mau a demora mais uma vez!
@caiolima86 show man, que bom que conseguiu resolver seu problema hahaha. 
Se conseguir exemplificar um pouco da utilizacao com a outra lib aqui, seria legal... Talvez outros tenham o mesmo problema ou alguem consiga enxergar alguma melhoria nessa lib.

Valeu abraco!
