### ISSUE TITLE
syntax error, unexpected token \"readonly\"

### ISSUE THREAD

**Issue by rafa-acioly** [discovery-tecnologia/dsc-mercado-livre#85]
Criei uma nova aplicação e ao tentar criar um novo anuncio com dados fakes para teste recebo o seguinte erro:

```
"message": "syntax error, unexpected token \"readonly\"",
"exception": "ParseError",
"file": "/var/www/html/vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/AnnotationDriver.php",
"line": 92
```

Ferramentas utilizadas:
Laravel: "^9.0"
PHP: 8.1.2

**Comment by dilowagner** [comment]
opa @rafa-acioly 
A hora que tiver um tempo, vou verificar, mas provavelmente porque atualizou a versao do PHP e da dependencia

**Comment by dilowagner** [comment]
Ola @rafa-acioly 
Obrigado pelo report, porem temos um problema grande aqui...

Confere nessa Issue
https://github.com/schmittjoh/serializer/issues/1331

Isso envolveria atualizar a jms/serializer para a versao 3 - o que precisa ser avaliado e teria um trabalho um pouco grande aqui.
O que eu posso dizer, eh que nao temos suporte para o PHP 8+ por enquanto :(

**Comment by dfikeda** [comment]
Eu consegui resolver essa situação, eu retirei as libs das pastas originais e copiei para o meu sistema, alterando o que precisava para fazer o sistema funcionar.
Na real eu não sei muito bem se está certo ou não, porém no momento está funcional.
Basicamente hard coding.
"require": {
        "php": "^8.0",
        "doctrine/annotations": "^1.13",
        "doctrine/cache": "^2.1",
        "doctrine/collections": "^1.6",
        "doctrine/instantiator": "^1.4",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "hardevine/shoppingcart": "^2.9",
        "jms/serializer": "1.3.1",
        "laravel/framework": "^8.12",
        "laravel/jetstream": "^2.1",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.6",
        "orangehill/iseed": "^3.0",
        "simplehtmldom/simplehtmldom": "^2.0@RC",
        "spatie/laravel-backup": "^6.15",
        "wireui/wireui": "^0.15.0"
    },

**Comment by dilowagner** [comment]
Opa, boa! 
Pode ser um caminho @dfikeda 
Consegue atualizar as dependencias do composer na sua maquina local e rodar os testes do PHP Unit pra ver se esta tudo certo?

**Comment by dilowagner** [comment]
Mais complementando, o problema aqui eh que eu acho perderiamos a compatibilidade com versoes anteriores do PHP (5, 7)
