### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\parse_query()

### ISSUE THREAD

**Issue by xxallanxx** [discovery-tecnologia/dsc-mercado-livre#88]
Call to undefined function GuzzleHttp\Psr7\parse_query()

  at C:\Users\allan\Documents\Cliente Eccomerce\codigo\vendor\dsc\mercado-livre\src\Handler\OAuth2ClientHandler.php:89
     85▕
     86▕             $token = $authorization->access_token;
     87▕         }
     88▕
  ➜  89▕         $queryparams = \GuzzleHttp\Psr7\parse_query($request->getUri()->getQuery());
     91▕
     92▕         return $request->withHeader('Authorization', "Bearer $token")
     93▕                        ->withUri(

Estou utilizando PHP 8.0.2 e Laravel 9.5

Pessoal, alguém sabe dizer se esse erro é um problema de compatibilidade ? Estou tentando consultar os dados do usuario e recebo essa mensagem, se alguém puder me ajudar agradeço muito !

**Comment by dilowagner** [comment]
Humm, 
Voce conseguiu instalar todas as dependencias corretamente com o composer @xxallanxx ?

**Comment by xxallanxx** [comment]
> Humm, você conseguiu instalar todas as dependências corretamente com o composer@xxallanxx?

Sim, instalou normal.. Mas eu resolvi utilizar a Lib só para pegar o token, e estou usando o http client do laravel para fazer o que eu preciso.Pelo jeito o problema é de compatibilidade mesmo...  Obrigado !

**Comment by dilowagner** [comment]
É.... 
Fechando aqui...
Infelizmente nao estou com tempo suficiente para atualizar essa lib :(
