### ISSUE TITLE
Biblioteca Ativa?

### ISSUE THREAD

**Issue by rafahcardoso** [discovery-tecnologia/dsc-mercado-livre#90]
Boa tarde pessoal,
Achei bem interessante essa biblioteca e precisarei fazer uma integração com o MercadoLivre.
Ela está funcional pra API do Mercado Livre atual?

**Comment by dilowagner** [comment]
Olá @rafahcardoso 
Só agora que vi essa mensagem hehe. Sinceramente amigo, não sei se tem muita gente usando ela (**inclusive devo arquivar em breve**)
Não tive muito tempo disponível para manter como eu gostaria. 
Acredito já estar desatualizada com a versão atual da API do Meli. 

Inclusive até a sdk oficial de PHP foi descontinuada. Sugiro vc procurar outra

**Comment by felipeabranches** [comment]
Poderia transferir para alguém ao invés de arquivar? Estou começando um desenvolvimento utilizandoo essa lib, e foi a melhor que encontrei

**Comment by dilowagner** [comment]
Legal, não vou arquivar por enquanto @felipeabranches 👍🏻
